[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/news/ti"
  to = "/.netlify/functions/news-ti"
  status = 200

[[redirects]]
  from = "/api/news/rh"
  to = "/.netlify/functions/news-rh"
  status = 200

[[redirects]]
  from = "/api/news/home"
  to = "/.netlify/functions/news-home"
  status = 200
